### ISSUE TITLE
BoundDropout error

### ISSUE THREAD

**Issue by ForeverZyh** [Verified-Intelligence/auto_LiRPA#55]
**Describe the bug**
BoundDropout complains, though I have forwarded the inputs.
```
Traceback (most recent call last):
  File "/Users/temp/repos/robust_CFX/models/IBPModel.py", line 284, in <module>
    lb, ub = model(method_opt="compute_bounds", x=dummy_input, C=c, method="IBP", final_node_name=None,
  File "/opt/anaconda3/envs/robust_CFX/lib/python3.8/site-packages/auto_LiRPA/bound_general.py", line 300, in __call__
    return self.compute_bounds(**kwargs)
  File "/opt/anaconda3/envs/robust_CFX/lib/python3.8/site-packages/auto_LiRPA/bound_general.py", line 1278, in compute_bounds
    self.ibp_lower, self.ibp_upper = self.IBP_general(node=final, C=C)
  File "/opt/anaconda3/envs/robust_CFX/lib/python3.8/site-packages/auto_LiRPA/interval_bound.py", line 30, in IBP_general
    self.IBP_general(
  File "/opt/anaconda3/envs/robust_CFX/lib/python3.8/site-packages/auto_LiRPA/interval_bound.py", line 30, in IBP_general
    self.IBP_general(
  File "/opt/anaconda3/envs/robust_CFX/lib/python3.8/site-packages/auto_LiRPA/interval_bound.py", line 30, in IBP_general
    self.IBP_general(
  [Previous line repeated 1 more time]
  File "/opt/anaconda3/envs/robust_CFX/lib/python3.8/site-packages/auto_LiRPA/interval_bound.py", line 42, in IBP_general
    node.interval = node.interval_propagate(*inp)
  File "/opt/anaconda3/envs/robust_CFX/lib/python3.8/site-packages/auto_LiRPA/operators/dropout.py", line 65, in interval_propagate
    self._check_forward()
  File "/opt/anaconda3/envs/robust_CFX/lib/python3.8/site-packages/auto_LiRPA/operators/dropout.py", line 36, in _check_forward
    raise RuntimeError('For a model with dropout in the training mode, '\
RuntimeError: For a model with dropout in the training mode, a clean forward pass must be called before bound computation
```

**To Reproduce**
```
import torch.nn as nn
import torch
from auto_LiRPA import BoundedModule


class FNN(nn.Module):
    def __init__(self):
        super(FNN, self).__init__()
        self.fc1 = nn.Linear(2, 4)
        self.fc2 = nn.Linear(4, 2)
        self.dropout = nn.Dropout(0.3)

    def forward(self, x):
        x = x.float()
        x = self.fc1(x)
        x = self.dropout(x)
        x = self.fc2(x)
        return x


model_ori = FNN()
batch_size = 100
x = torch.normal(0, 0.2, (batch_size, 2))
y = torch.ones((batch_size,))

dummy_input = x[:2]
model = BoundedModule(model_ori, dummy_input, bound_opts={
    'relu': "same-slope", 'sparse_intermediate_bounds': False,
    'sparse_conv_intermediate_bounds': False, 'sparse_intermediate_bounds_with_ibp': False})
final_name1 = model.final_name

model.train()
c = torch.tensor([[-1, 1], [-1, 1]]).type_as(y)
dummy_out = model(dummy_input)
lb, ub = model(method_opt="compute_bounds", x=dummy_input, C=c, method="IBP", final_node_name=None,
               no_replicas=True)

```

**System configuration:**
 - Python version: Python 3.8
 - Pytorch Version: PyTorch 1.12
 - Have you tried to reproduce the problem in a cleanly created conda/virtualenv environment using official installation instructions and the latest code on the main branch?: Yes

**Additional context**
I find there are two BoundDropout in the computational graph, there should be only one. 
Also, when executing the last line, all the `self.mask` in the BoundDropout object are cleaned in the initialization.

**Comment by ForeverZyh** [comment]
I realized that I should not forward with `x=dummy_input` in the last call of `model`.
