### ISSUE TITLE
CUDA out-of-memory when running examples/vision/jacobian.py

### ISSUE THREAD

**Issue by nhamlv-55** [Verified-Intelligence/auto_LiRPA#68]
**Describe the bug**
When trying the script `examples/vision/jacobian.py` on a 1080Ti I ran into an CUDA out-of-memory error. The log says that I should file a ticket.
```
python jacobian.py
Files already downloaded and verified
Model: Sequential(
  (0): Conv2d(3, 4, kernel_size=(3, 3), stride=(1, 1))
  (1): ReLU()
  (2): Conv2d(4, 4, kernel_size=(3, 3), stride=(1, 1))
  (3): ReLU()
  (4): Flatten(start_dim=1, end_dim=-1)
  (5): Linear(in_features=3136, out_features=32, bias=True)
  (6): ReLU()
  (7): Linear(in_features=32, out_features=10, bias=True)
)
/home/nle/anaconda3/envs/py39/lib/python3.9/site-packages/torch/nn/modules/conv.py:456: UserWarning: Applied workaround for CuDNN issue, install nvrtc.so (Triggered internally at /opt/conda/conda-bld/pytorch_1708025831482/work/aten/src/ATen/native/cudnn/Conv_v8.cpp:80.)
  return F.conv2d(input, weight, bias, self.stride,
[W NNPACK.cpp:64] Could not initialize NNPACK! Reason: Unsupported hardware.
/home/nle/anaconda3/envs/py39/lib/python3.9/site-packages/auto_LiRPA-0.4.0-py3.9.egg/auto_LiRPA/operators/gradient_modules.py:85: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if grad_last.numel() == inp.numel():
/home/nle/anaconda3/envs/py39/lib/python3.9/site-packages/auto_LiRPA-0.4.0-py3.9.egg/auto_LiRPA/operators/gradient_modules.py:41: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  + 2 * self.padding - 1 - (int(self.weight.size()[2] - 1) * self.dilation))
/home/nle/anaconda3/envs/py39/lib/python3.9/site-packages/auto_LiRPA-0.4.0-py3.9.egg/auto_LiRPA/bound_general.py:880: UserWarning: Creating an identity matrix with size 3136x3136 for node BoundReshape(name=/grad/12, inputs=[/grad/13, /grad/13/tmp/16], perturbed=True). This may indicate poor performance for bound computation. If you see this message on a small network please submit a bug report.
  sparse_C = self.get_sparse_C(
Traceback (most recent call last):
  File "/home/nle/opt/ogAutoLirpa/examples/vision/jacobian.py", line 142, in <module>
    run_jacobian_examples()
  File "/home/nle/opt/ogAutoLirpa/examples/vision/jacobian.py", line 138, in run_jacobian_examples
    return compute_jacobians(model_ori, x0, device=device)
  File "/home/nle/opt/ogAutoLirpa/examples/vision/jacobian.py", line 67, in compute_jacobians
    lower, upper = model.compute_jacobian_bounds(x)
  File "/home/nle/anaconda3/envs/py39/lib/python3.9/site-packages/auto_LiRPA-0.4.0-py3.9.egg/auto_LiRPA/jacobian.py", line 373, in compute_jacobian_bounds
    self.compute_bounds(
  File "/home/nle/anaconda3/envs/py39/lib/python3.9/site-packages/auto_LiRPA-0.4.0-py3.9.egg/auto_LiRPA/bound_general.py", line 1193, in compute_bounds
    ret1 = self._get_optimized_bounds(bound_side='lower', **kwargs)
  File "/home/nle/anaconda3/envs/py39/lib/python3.9/site-packages/auto_LiRPA-0.4.0-py3.9.egg/auto_LiRPA/optimized_bounds.py", line 638, in _get_optimized_bounds
    loss.backward()
  File "/home/nle/anaconda3/envs/py39/lib/python3.9/site-packages/torch/_tensor.py", line 522, in backward
    torch.autograd.backward(
  File "/home/nle/anaconda3/envs/py39/lib/python3.9/site-packages/torch/autograd/__init__.py", line 266, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 676.00 MiB. GPU 0 has a total capacity of 10.92 GiB of which 188.56 MiB is free. Including non-PyTorch memory, this process has 8.48 GiB memory in use. Of the allocated memory 6.16 GiB is allocated by PyTorch, and 1.54 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```
**To Reproduce**
Clone the main branch of auto_LiRPA.
Change `pytorch_version_u` to 2.2.1 since this is the version I'm using
Run `examples/vision/jacobian.py`
Install using `python setup.py install`

**Comment by shizhouxing** [comment]
Hi @nhamlv-55, this model needs at least 32G GPU memory. You may try a smaller model.

We will release a new version of the library soon where we have revised the code for jacobian and there is an example using a small model.
